spring:
  application:
    name: TripPlanner

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: saurav
    password: saurav
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_APIKEY}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true


application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #1 day
      refresh-token:
        expiration: 604800000 #7 day
  email:
    from: noreplytraventure@gmail.com



server:
  port: 8030
